### ISSUE TITLE
Support ordering with Django 1.7's custom lookups

### ISSUE THREAD

**Issue by aidanlister** [djangonauts/django-hstore#62]
This is re-opening issue #31, as we should be able to support ordering now in Django 1.7 which is almost at a stable release, with a custom lookup:
https://docs.djangoproject.com/en/dev/howto/custom-lookups/

**Comment by aidanlister** [comment]
Does this mean it's implemented or were you waiting on a reply from me? :)

**Comment by nemesisdesign** [comment]
No this is not implemented and it doesn't look like anybody is going to.
Latelly we have been receiving many issues, feature requests, and some pull requests. Going all through this takes time which sometimes we don't have. I would prefer to keep open only bug reports or pull requests in order to stay focused and optimize the little time we have.
